# Generated by Django 5.2.18 on 2026-10-07 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(default="flight", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("processing", "Processing"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("status_detail", models.CharField(blank=True, max_length=255)),
                ("test_mode", models.BooleanField(default=False)),
                ("offer_id", models.CharField(max_length=64)),
                (
                    "duffel_order_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("booking_reference", models.CharField(blank=True, max_length=16)),
                ("total_amount", models.DecimalField(decimal_places=3, max_digits=14)),
                ("duffel_amount", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("currency", models.CharField(max_length=3)),
                ("airline", models.JSONField(blank=True, default=dict)),
                ("slices", models.JSONField(blank=True, default=list)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("baggage", models.JSONField(blank=True, default=list)),
                ("passengers", models.JSONField(blank=True, default=list)),
                ("first_departure", models.DateTimeField(blank=True, null=True)),
                ("has_airline_changes", models.BooleanField(default=False)),
                ("passenger_input", models.JSONField(blank=True, default=dict)),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("refund_status", models.CharField(blank=True, max_length=32)),
                ("refund_id", models.CharField(blank=True, max_length=128)),
                ("cancellation_id", models.CharField(blank=True, max_length=64)),
                ("needs_attention", models.BooleanField(db_index=True, default=False)),
                ("attention_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("event_id", models.CharField(max_length=128)),
                ("event_type", models.CharField(blank=True, max_length=128)),
                ("object_id", models.CharField(blank=True, max_length=128)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="uniq_webhook_event"
                    )
                ],
            },
        ),
    ]
