// File: Core/Services/Learning/TravelProfileStore.swift
//
// Owns the durable travel-signal log and the derived TravelProfile. Mirrors the
// shape of IRISMemory: a @MainActor ObservableObject singleton backed by
// UserDefaults, fully offline. Recording is ALWAYS gated by the user's consent
// (UserPreferences.learningEnabled + the per-source flags); when consent is off,
// `record` is a no-op. "Clear Local Data" wipes the signal log via its key.

import Foundation

@MainActor
@Observable
final class TravelProfileStore {

    static let shared = TravelProfileStore()

    /// The latest derived profile. Recomputed whenever signals change or on demand.
    private(set) var profile: TravelProfile = .empty()
    private(set) var signalCount: Int = 0
    /// A short natural-language "travel persona" generated by Claude from the profile.
    /// Cached so we don't re-call the model on every read. Empty until generated.
    private(set) var persona: String = ""
    private let personaKey = "jetsetter_travel_persona"

    /// Persisted under the same `jetsetter_*` convention as other stores so it's
    /// covered by Settings → Clear Local Data.
    static let storageKey = "jetsetter_travel_signals"
    private let maxSignals = 2000

    private var signals: [TravelSignal] = []

    private let encoder: JSONEncoder = {
        let e = JSONEncoder(); e.dateEncodingStrategy = .iso8601; return e
    }()
    private let decoder: JSONDecoder = {
        let d = JSONDecoder(); d.dateDecodingStrategy = .iso8601; return d
    }()

    private init() {
        load()
        // Defer the first profile computation off the synchronous init path so a
        // first access (e.g. during Home load) doesn't decode three stores inline.
        Task { @MainActor in self.recompute() }
    }

    // MARK: - Recording (consent-gated)

    /// Records a signal if (a) learning is enabled and (b) the per-source toggle for
    /// this kind is on. Silently ignored otherwise — callers can fire unconditionally.
    func record(
        _ kind: TravelSignal.Kind,
        value: String,
        attributes: [String: String] = [:],
        source: String = ""
    ) {
        guard isAllowed(kind) else { return }
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let signal = TravelSignal(kind: kind, value: trimmed, attributes: attributes, source: source)
        signals.append(signal)
        if signals.count > maxSignals {
            signals.removeFirst(signals.count - maxSignals)
        }
        save()
        recompute()

        // Best-effort persistence of this signal to SupabaseService. NOTE: the
        // travel-signal methods there are on-device UserDefaults stubs today (no
        // network egress), so the learning layer remains fully on-device — but this
        // mirror is cleared by clearLearnedData() so it can't outlive a data wipe.
        Task { try? await SupabaseService.shared.syncTravelSignals([signal]) }
    }

    /// Merges any signals held by SupabaseService not already present locally (dedup
    /// by id). Intended to let a profile follow the user across devices once the sync
    /// stubs are backed by a real backend; today it reads the on-device mirror only.
    func mergeFromCloud() async {
        guard UserPreferences.shared.learningEnabled,
              await SupabaseService.shared.isSignedIn,
              let remote = try? await SupabaseService.shared.fetchTravelSignals() else { return }
        let existing = Set(signals.map(\.id))
        let fresh = remote.filter { !existing.contains($0.id) }
        guard !fresh.isEmpty else { return }
        signals.append(contentsOf: fresh)
        signals.sort { $0.timestamp < $1.timestamp }
        if signals.count > maxSignals { signals.removeFirst(signals.count - maxSignals) }
        save()
        recompute()
    }

    private func isAllowed(_ kind: TravelSignal.Kind) -> Bool {
        let prefs = UserPreferences.shared
        guard prefs.learningEnabled else { return false }
        switch kind {
        case .receiptScanned, .expenseLogged:
            return prefs.learnFromReceipts
        case .seatChosen:
            return prefs.learnFromCheckIns
        case .flightFlown, .tripCompleted, .placeVisited:
            return prefs.learnFromTrips
        case .loyaltyAdded, .suggestionFeedback:
            return true  // governed by the master switch only
        }
    }

    // MARK: - Profile

    /// Rebuilds the profile from the signal log plus the history already on device.
    /// When learning is disabled, the profile collapses to empty so nothing derived
    /// is surfaced to IRIS or the transparency screen (consent-respecting).
    func recompute() {
        signalCount = signals.count
        guard UserPreferences.shared.learningEnabled else {
            profile = .empty()
            // Turning learning off must also drop any cached persona immediately
            // (not just on the next launch), so nothing derived stays surfaced.
            if !persona.isEmpty {
                persona = ""
                UserDefaults.standard.removeObject(forKey: personaKey)
            }
            return
        }
        profile = TravelProfileEngine.buildProfile(
            signals: signals,
            boardingPasses: loadBoardingPasses(),
            trips: loadTrips(),
            expenses: loadExpenses()
        )
    }

    // MARK: - Persona enrichment (Claude)

    /// Generates a short natural-language persona from the profile via Claude (through
    /// the existing proxy in AIService) and caches it. No-op when learning is off or
    /// the profile is empty (and clears any stale cached persona in that case).
    func refreshPersona() async {
        guard UserPreferences.shared.learningEnabled, !profile.isEmpty else {
            if !persona.isEmpty {
                persona = ""
                UserDefaults.standard.removeObject(forKey: personaKey)
            }
            return
        }
        let summary = profile.summaryForPrompt()
        let prompt = """
        Here is a traveler's learned profile:

        \(summary)

        Write a warm, 2–3 sentence "travel persona" in the second person ("You're…") that captures their style. Output only the paragraph — no preamble, no lists.
        """
        let system = "You write concise, friendly traveler-persona descriptions. Output only the paragraph."

        var accumulated = ""
        do {
            for try await chunk in AIService.shared.streamResponse(prompt: prompt, history: [], systemPrompt: system) {
                accumulated = chunk   // AIService yields cumulative snapshots
            }
        } catch {
            return   // leave any existing persona untouched on failure
        }
        // Re-check consent/profile AFTER the await: the user may have turned learning
        // off or wiped data while the model call was in flight — don't resurrect it.
        guard UserPreferences.shared.learningEnabled, !profile.isEmpty else { return }
        let trimmed = String(accumulated.trimmingCharacters(in: .whitespacesAndNewlines).prefix(600))
        guard !trimmed.isEmpty else { return }
        persona = trimmed
        UserDefaults.standard.set(trimmed, forKey: personaKey)
    }

    // MARK: - Suggestion feedback loop

    /// Records whether the user accepted or dismissed a proactive suggestion of a
    /// given kind. Used to adapt the proactive surface (suppress nagging nudges,
    /// reinforce welcomed ones). Consent-gated like every other signal.
    func recordSuggestionFeedback(kind: String, accepted: Bool) {
        record(.suggestionFeedback, value: kind,
               attributes: ["accepted": accepted ? "true" : "false"],
               source: "suggestion")
        // Mirror into the lightweight metrics ledger so acceptance rate per kind is
        // queryable without replaying the whole signal log.
        SuggestionMetricsStore.shared.recordFeedback(kind: kind, accepted: accepted)
    }

    /// Recent accept/dismiss tallies for a suggestion kind, windowed to the last
    /// `days` days. Windowing means a nudge the user dismissed a year ago (before
    /// their habits changed) no longer silences it forever; surfacing `accepts` lets
    /// IRISTriggers keep a welcomed nudge alive rather than only demoting on dismissal.
    func suggestionFeedback(
        forKind kind: String,
        withinDays days: Int = 90,
        now: Date = Date()
    ) -> (accepts: Int, dismisses: Int) {
        let cutoff = now.addingTimeInterval(-Double(days) * 86_400)
        var accepts = 0, dismisses = 0
        for s in signals where s.kind == .suggestionFeedback && s.value == kind && s.timestamp >= cutoff {
            if s.attributes["accepted"] == "true" { accepts += 1 } else { dismisses += 1 }
        }
        return (accepts, dismisses)
    }

    // MARK: - User-facing controls

    /// Forgets all learned signals (the profile collapses to empty on recompute).
    func clearLearnedData() {
        signals = []
        persona = ""
        UserDefaults.standard.removeObject(forKey: personaKey)
        save()
        recompute()
        // The metrics ledger is derived from learned behavior — wipe it too.
        SuggestionMetricsStore.shared.reset()
        // A copy of every signal is mirrored into SupabaseService's local store on
        // record(); clear that shadow copy as well, or learned data would survive a
        // "Clear Local Data" tap. (These sync methods are on-device stubs today.)
        Task { await SupabaseService.shared.clearTravelSignals() }
    }

    // MARK: - Persistence

    private func load() {
        // Only surface the cached persona when learning is enabled. With consent off,
        // the profile collapses to empty on recompute(); the persona must stay empty to
        // match (and any stale cache is cleared so disabling learning wipes it).
        if UserPreferences.shared.learningEnabled {
            persona = UserDefaults.standard.string(forKey: personaKey) ?? ""
        } else {
            persona = ""
            UserDefaults.standard.removeObject(forKey: personaKey)
        }
        guard let data = UserDefaults.standard.data(forKey: Self.storageKey),
              let decoded = try? decoder.decode([TravelSignal].self, from: data) else { return }
        signals = decoded
    }

    private func save() {
        guard let data = try? encoder.encode(signals) else { return }
        UserDefaults.standard.set(data, forKey: Self.storageKey)
    }

    // MARK: - Reading existing on-device history

    private func loadBoardingPasses() -> [WalletItem] {
        decode([WalletItem].self, key: "jetsetter_wallet_items")?
            .filter { $0.itemType == .boardingPass } ?? []
    }
    private func loadTrips() -> [Trip] { decode([Trip].self, key: "jetsetter_trips") ?? [] }
    private func loadExpenses() -> [Expense] { decode([Expense].self, key: "jetsetter_expenses") ?? [] }

    /// Tolerant decode: other stores encode dates inconsistently (trips use ISO-8601,
    /// expenses use the default numeric strategy), so try ISO-8601 first and fall back
    /// to the default. Avoids silently dropping history without risky data migration.
    private func decode<T: Decodable>(_ type: T.Type, key: String) -> T? {
        guard let data = UserDefaults.standard.data(forKey: key) else { return nil }
        if let v = try? decoder.decode(T.self, from: data) { return v }   // .iso8601
        return try? JSONDecoder().decode(T.self, from: data)              // .deferredToDate
    }
}

// MARK: - Suggestion & IRIS metrics (lightweight on-device analytics)

/// A tiny, fully on-device metrics ledger so the team can answer two questions the
/// app currently can't: "is the proactive surface working?" and "does personalization
/// help IRIS?" — without any server, SDK, or PII leaving the device. Consent-gated by
/// the same learning master switch, and wiped by "Clear Local Data" (via `reset()`).
///
/// Per suggestion kind it tracks unique impressions (deduped by dismissal key so
/// repeated Home reloads don't inflate the count), accepts, and dismisses — from which
/// acceptance rate follows. For IRIS chat it tracks turns where the learned profile was
/// injected vs. not and, when the UI offers a thumbs, helpful votes for each bucket —
/// a poor-man's A/B on whether profile context actually improves replies.
@MainActor
@Observable
final class SuggestionMetricsStore {

    static let shared = SuggestionMetricsStore()

    struct KindMetrics: Codable, Equatable {
        var impressions = 0
        var accepts = 0
        var dismisses = 0
        var acceptanceRate: Double { impressions > 0 ? Double(accepts) / Double(impressions) : 0 }
    }

    struct TurnMetrics: Codable, Equatable {
        var turnsWithProfile = 0
        var turnsWithoutProfile = 0
        var helpfulWithProfile = 0
        var unhelpfulWithProfile = 0
        var helpfulWithoutProfile = 0
        var unhelpfulWithoutProfile = 0

        /// Helpful-rate lift from injecting the learned profile (nil until both
        /// buckets have votes). Positive → profile context is helping.
        var profileLift: Double? {
            let withTotal = helpfulWithProfile + unhelpfulWithProfile
            let withoutTotal = helpfulWithoutProfile + unhelpfulWithoutProfile
            guard withTotal > 0, withoutTotal > 0 else { return nil }
            return Double(helpfulWithProfile) / Double(withTotal)
                 - Double(helpfulWithoutProfile) / Double(withoutTotal)
        }
    }

    private(set) var byKind: [String: KindMetrics] = [:]
    private(set) var turns = TurnMetrics()
    /// Dismissal keys already counted as an impression (so a suggestion re-surfaced
    /// across Home reloads counts once, not once per load).
    private var seenImpressionKeys: Set<String> = []

    private static let storageKey = "jetsetter_suggestion_metrics"
    private let encoder: JSONEncoder = { let e = JSONEncoder(); e.dateEncodingStrategy = .iso8601; return e }()
    private let decoder: JSONDecoder = { let d = JSONDecoder(); d.dateDecodingStrategy = .iso8601; return d }()

    private init() { load() }

    private var consented: Bool { UserPreferences.shared.learningEnabled }

    // MARK: Recording

    func recordImpression(kind: String, dedupKey: String) {
        guard consented, !seenImpressionKeys.contains(dedupKey) else { return }
        seenImpressionKeys.insert(dedupKey)
        byKind[kind, default: .init()].impressions += 1
        save()
    }

    func recordFeedback(kind: String, accepted: Bool) {
        guard consented else { return }
        if accepted { byKind[kind, default: .init()].accepts += 1 }
        else        { byKind[kind, default: .init()].dismisses += 1 }
        save()
    }

    /// Call once per IRIS chat turn, noting whether the learned profile summary was
    /// non-empty (and therefore injected into her instructions) for that turn.
    func recordIRISTurn(profileInjected: Bool) {
        guard consented else { return }
        if profileInjected { turns.turnsWithProfile += 1 } else { turns.turnsWithoutProfile += 1 }
        save()
    }

    /// Call when the user rates an IRIS reply (thumbs up/down), tagging whether that
    /// turn had profile context. Feeds `TurnMetrics.profileLift`.
    func recordHelpfulVote(profileInjected: Bool, helpful: Bool) {
        guard consented else { return }
        switch (profileInjected, helpful) {
        case (true, true):   turns.helpfulWithProfile += 1
        case (true, false):  turns.unhelpfulWithProfile += 1
        case (false, true):  turns.helpfulWithoutProfile += 1
        case (false, false): turns.unhelpfulWithoutProfile += 1
        }
        save()
    }

    func reset() {
        byKind = [:]
        turns = .init()
        seenImpressionKeys = []
        UserDefaults.standard.removeObject(forKey: Self.storageKey)
    }

    // MARK: Persistence

    private struct Snapshot: Codable {
        var byKind: [String: KindMetrics]
        var turns: TurnMetrics
        var seenImpressionKeys: [String]
    }

    private func load() {
        guard let data = UserDefaults.standard.data(forKey: Self.storageKey),
              let snap = try? decoder.decode(Snapshot.self, from: data) else { return }
        byKind = snap.byKind
        turns = snap.turns
        seenImpressionKeys = Set(snap.seenImpressionKeys)
    }

    private func save() {
        let snap = Snapshot(byKind: byKind, turns: turns, seenImpressionKeys: Array(seenImpressionKeys))
        guard let data = try? encoder.encode(snap) else { return }
        UserDefaults.standard.set(data, forKey: Self.storageKey)
    }
}
