// File: Core/Services/Learning/TravelProfileStore.swift
//
// Owns the durable travel-signal log and the derived TravelProfile. Mirrors the
// shape of IRISMemory: a @MainActor ObservableObject singleton backed by
// UserDefaults, fully offline. Recording is ALWAYS gated by the user's consent
// (UserPreferences.learningEnabled + the per-source flags); when consent is off,
// `record` is a no-op. "Clear Local Data" wipes the signal log via its key.

import Foundation
import Combine

@MainActor
final class TravelProfileStore: ObservableObject {

    static let shared = TravelProfileStore()

    /// The latest derived profile. Recomputed whenever signals change or on demand.
    @Published private(set) var profile: TravelProfile = .empty()
    @Published private(set) var signalCount: Int = 0
    /// A short natural-language "travel persona" generated by Claude from the profile.
    /// Cached so we don't re-call the model on every read. Empty until generated.
    @Published private(set) var persona: String = ""
    private let personaKey = "jetsetter_travel_persona"

    /// Persisted under the same `jetsetter_*` convention as other stores so it's
    /// covered by Settings → Clear Local Data.
    static let storageKey = "jetsetter_travel_signals"
    private let maxSignals = 2000

    private var signals: [TravelSignal] = []

    private let encoder: JSONEncoder = {
        let e = JSONEncoder(); e.dateEncodingStrategy = .iso8601; return e
    }()
    private let decoder: JSONDecoder = {
        let d = JSONDecoder(); d.dateDecodingStrategy = .iso8601; return d
    }()

    private init() {
        load()
        // Defer the first profile computation off the synchronous init path so a
        // first access (e.g. during Home load) doesn't decode three stores inline.
        Task { @MainActor in self.recompute() }
    }

    // MARK: - Recording (consent-gated)

    /// Records a signal if (a) learning is enabled and (b) the per-source toggle for
    /// this kind is on. Silently ignored otherwise — callers can fire unconditionally.
    func record(
        _ kind: TravelSignal.Kind,
        value: String,
        attributes: [String: String] = [:],
        source: String = ""
    ) {
        guard isAllowed(kind) else { return }
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let signal = TravelSignal(kind: kind, value: trimmed, attributes: attributes, source: source)
        signals.append(signal)
        if signals.count > maxSignals {
            signals.removeFirst(signals.count - maxSignals)
        }
        save()
        recompute()

        // Best-effort cloud sync of just this new signal. No-op when signed out
        // (ensureAuthenticated throws, swallowed). Consent already enforced above.
        Task { try? await SupabaseService.shared.syncTravelSignals([signal]) }
    }

    /// Pulls cloud signals and merges any not already present locally (dedup by id),
    /// so a learned profile follows the user across devices. Consent + sign-in gated.
    func mergeFromCloud() async {
        guard UserPreferences.shared.learningEnabled,
              await SupabaseService.shared.isSignedIn,
              let remote = try? await SupabaseService.shared.fetchTravelSignals() else { return }
        let existing = Set(signals.map(\.id))
        let fresh = remote.filter { !existing.contains($0.id) }
        guard !fresh.isEmpty else { return }
        signals.append(contentsOf: fresh)
        signals.sort { $0.timestamp < $1.timestamp }
        if signals.count > maxSignals { signals.removeFirst(signals.count - maxSignals) }
        save()
        recompute()
    }

    private func isAllowed(_ kind: TravelSignal.Kind) -> Bool {
        let prefs = UserPreferences.shared
        guard prefs.learningEnabled else { return false }
        switch kind {
        case .receiptScanned, .expenseLogged:
            return prefs.learnFromReceipts
        case .seatChosen:
            return prefs.learnFromCheckIns
        case .flightFlown, .tripCompleted, .placeVisited:
            return prefs.learnFromTrips
        case .loyaltyAdded, .suggestionFeedback:
            return true  // governed by the master switch only
        }
    }

    // MARK: - Profile

    /// Rebuilds the profile from the signal log plus the history already on device.
    /// When learning is disabled, the profile collapses to empty so nothing derived
    /// is surfaced to IRIS or the transparency screen (consent-respecting).
    func recompute() {
        signalCount = signals.count
        guard UserPreferences.shared.learningEnabled else {
            profile = .empty()
            return
        }
        profile = TravelProfileEngine.buildProfile(
            signals: signals,
            boardingPasses: loadBoardingPasses(),
            trips: loadTrips(),
            expenses: loadExpenses()
        )
    }

    // MARK: - Persona enrichment (Claude)

    /// Generates a short natural-language persona from the profile via Claude (through
    /// the existing proxy in AIService) and caches it. No-op when learning is off or
    /// the profile is empty (and clears any stale cached persona in that case).
    func refreshPersona() async {
        guard UserPreferences.shared.learningEnabled, !profile.isEmpty else {
            if !persona.isEmpty {
                persona = ""
                UserDefaults.standard.removeObject(forKey: personaKey)
            }
            return
        }
        let summary = profile.summaryForPrompt()
        let prompt = """
        Here is a traveler's learned profile:

        \(summary)

        Write a warm, 2–3 sentence "travel persona" in the second person ("You're…") that captures their style. Output only the paragraph — no preamble, no lists.
        """
        let system = "You write concise, friendly traveler-persona descriptions. Output only the paragraph."

        var accumulated = ""
        do {
            for try await chunk in AIService.shared.streamResponse(prompt: prompt, history: [], systemPrompt: system) {
                accumulated = chunk   // AIService yields cumulative snapshots
            }
        } catch {
            return   // leave any existing persona untouched on failure
        }
        // Re-check consent/profile AFTER the await: the user may have turned learning
        // off or wiped data while the model call was in flight — don't resurrect it.
        guard UserPreferences.shared.learningEnabled, !profile.isEmpty else { return }
        let trimmed = String(accumulated.trimmingCharacters(in: .whitespacesAndNewlines).prefix(600))
        guard !trimmed.isEmpty else { return }
        persona = trimmed
        UserDefaults.standard.set(trimmed, forKey: personaKey)
    }

    // MARK: - Suggestion feedback loop

    /// Records whether the user accepted or dismissed a proactive suggestion of a
    /// given kind. Used to adapt the proactive surface (suppress nagging nudges,
    /// reinforce welcomed ones). Consent-gated like every other signal.
    func recordSuggestionFeedback(kind: String, accepted: Bool) {
        record(.suggestionFeedback, value: kind,
               attributes: ["accepted": accepted ? "true" : "false"],
               source: "suggestion")
    }

    /// How many times the user has dismissed (not accepted) suggestions of this kind.
    /// IRISTriggers uses this to stop surfacing a nudge the user keeps waving away.
    func dismissedCount(forSuggestionKind kind: String) -> Int {
        signals.filter {
            $0.kind == .suggestionFeedback && $0.value == kind && $0.attributes["accepted"] == "false"
        }.count
    }

    // MARK: - User-facing controls

    /// Forgets all learned signals (the profile collapses to empty on recompute).
    func clearLearnedData() {
        signals = []
        persona = ""
        UserDefaults.standard.removeObject(forKey: personaKey)
        save()
        recompute()
    }

    // MARK: - Persistence

    private func load() {
        persona = UserDefaults.standard.string(forKey: personaKey) ?? ""
        guard let data = UserDefaults.standard.data(forKey: Self.storageKey),
              let decoded = try? decoder.decode([TravelSignal].self, from: data) else { return }
        signals = decoded
    }

    private func save() {
        guard let data = try? encoder.encode(signals) else { return }
        UserDefaults.standard.set(data, forKey: Self.storageKey)
    }

    // MARK: - Reading existing on-device history

    private func loadBoardingPasses() -> [WalletItem] {
        decode([WalletItem].self, key: "jetsetter_wallet_items")?
            .filter { $0.itemType == .boardingPass } ?? []
    }
    private func loadTrips() -> [Trip] { decode([Trip].self, key: "jetsetter_trips") ?? [] }
    private func loadExpenses() -> [Expense] { decode([Expense].self, key: "jetsetter_expenses") ?? [] }

    /// Tolerant decode: other stores encode dates inconsistently (trips use ISO-8601,
    /// expenses use the default numeric strategy), so try ISO-8601 first and fall back
    /// to the default. Avoids silently dropping history without risky data migration.
    private func decode<T: Decodable>(_ type: T.Type, key: String) -> T? {
        guard let data = UserDefaults.standard.data(forKey: key) else { return nil }
        if let v = try? decoder.decode(T.self, from: data) { return v }   // .iso8601
        return try? JSONDecoder().decode(T.self, from: data)              // .deferredToDate
    }
}
