// File: Core/Services/Expense/Providers/EmailPDFProvider.swift
//
// The universal fallback. Generates a multi-page PDF expense report and opens
// MFMailComposeViewController with it attached. Works for ANY expense system
// the user's company uses.

import Foundation
import UIKit
import MessageUI

@MainActor
final class EmailPDFProvider: NSObject, ExpenseExportProvider {

    let id = "email_pdf"
    let displayName = "Email Expense Report"
    let tagline = "Send a polished PDF to your approver"
    let brandColorHex = "#3B9EF0"
    let systemImage = "envelope.fill"
    let authKind: ExpenseProviderAuthKind = .none

    static let shared = EmailPDFProvider()
    private override init() {}

    private var pendingContinuation: CheckedContinuation<ExportBatchResult, Error>?
    private var pendingExpenses: [Expense] = []
    private var pendingTripName: String = ""

    func isConnected() async -> Bool { true }    // Always available
    func connect() async throws -> Bool { true }
    func disconnect() async {}

    // MARK: - Submit

    func submit(trip: Trip?, expenses: [Expense]) async throws -> ExportBatchResult {
        guard MFMailComposeViewController.canSendMail() else {
            throw ExpenseExportError.providerFailure("This device can't send mail. Set up the Mail app first.")
        }

        let pdfData = PDFExpenseReportRenderer.render(
            trip: trip,
            expenses: expenses
        )

        let composer = MFMailComposeViewController()
        composer.mailComposeDelegate = self
        composer.setSubject("Expense Report — \(trip?.name ?? "Travel")")
        composer.setMessageBody(messageBody(trip: trip, expenses: expenses), isHTML: false)
        composer.addAttachmentData(
            pdfData,
            mimeType: "application/pdf",
            fileName: "Expense_Report_\(trip?.name.replacingOccurrences(of: " ", with: "_") ?? "Travel").pdf"
        )

        guard let root = activeRootViewController() else {
            throw ExpenseExportError.providerFailure("Could not present mail composer.")
        }
        root.present(composer, animated: true)

        pendingExpenses = expenses
        pendingTripName = trip?.name ?? "Travel"

        // Suspend until the delegate callback fires.
        return try await withCheckedThrowingContinuation { continuation in
            self.pendingContinuation = continuation
        }
    }

    // MARK: - Helpers

    private func messageBody(trip: Trip?, expenses: [Expense]) -> String {
        let total = expenses.reduce(0) { $0 + $1.amount }
        let currency = expenses.first?.currency ?? "USD"
        var lines: [String] = [
            "Hi,",
            "",
            "Attached is my expense report\(trip.map { " for \($0.name)" } ?? "")."
        ]
        if let trip = trip {
            let f = DateFormatter(); f.dateStyle = .medium
            lines.append("Trip dates: \(f.string(from: trip.startDate)) – \(f.string(from: trip.endDate))")
            lines.append("Destination: \(trip.destination)")
        }
        lines.append("")
        lines.append(String(format: "Total: %@ %.2f across %d items", currency, total, expenses.count))
        lines.append("")
        lines.append("Generated by JetSetter Pro.")
        return lines.joined(separator: "\n")
    }

    private func activeRootViewController() -> UIViewController? {
        UIApplication.shared.connectedScenes
            .compactMap { $0 as? UIWindowScene }
            .flatMap { $0.windows }
            .first { $0.isKeyWindow }?
            .rootViewController?
            .topMostPresented()
    }
}

// MARK: - MFMailComposeViewControllerDelegate

extension EmailPDFProvider: MFMailComposeViewControllerDelegate {

    nonisolated func mailComposeController(
        _ controller: MFMailComposeViewController,
        didFinishWith result: MFMailComposeResult,
        error: Error?
    ) {
        controller.dismiss(animated: true)
        Task { @MainActor in
            self.handleMailFinish(result: result, error: error)
        }
    }

    private func handleMailFinish(result: MFMailComposeResult, error: Error?) {
        guard let continuation = pendingContinuation else { return }
        pendingContinuation = nil

        let now = Date()
        switch result {
        case .sent:
            let perExpense = Dictionary(
                uniqueKeysWithValues: pendingExpenses.map { ($0.id, ExportOutcome.submitted(remoteID: "emailed")) }
            )
            continuation.resume(returning: ExportBatchResult(
                providerID: id, providerName: displayName,
                submittedAt: now, perExpense: perExpense
            ))
        case .saved:
            continuation.resume(throwing: ExpenseExportError.userCancelled)
        case .cancelled:
            continuation.resume(throwing: ExpenseExportError.userCancelled)
        case .failed:
            continuation.resume(throwing: ExpenseExportError.providerFailure(
                error?.localizedDescription ?? "Mail send failed."
            ))
        @unknown default:
            continuation.resume(throwing: ExpenseExportError.providerFailure("Unknown mail result."))
        }
        pendingExpenses = []
        pendingTripName = ""
    }
}

// MARK: - UIViewController helper

private extension UIViewController {
    func topMostPresented() -> UIViewController {
        if let presented = presentedViewController { return presented.topMostPresented() }
        return self
    }
}
